---
- name: 'ASA Config'
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: retrieve contexts of the ASA 
      asa_command:
        commands:
          - changeto system
          - show run context | inc ^context
        provider:
          username: "kamil.zuk"
          password: "January18"
          authorize: yes
          auth_pass: "January18"
          context: all
      register: output

    - copy: 
        content: "{{ output.stdout_lines }}"
        dest: "/var/lib/awx/Contexts/{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}-Context-of-{{ inventory_hostname }}"
    #- debug: msg="{{ item }}"
    #- name: switch to contexts
    #  asa_command:
     #   context: all
          #-{{ item }}
     # with_lines: cat /var/lib/awx/Contexts/{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}-Context-of-{{ inventory_hostname }}  
     # register: contexts
      
    - debug: msg="{{ output.stdout_lines }}"
      
      
#    - set_fact:
#        context={{ output.stdout_lines }}
#    - copy: 
#        content: "{{ output.stdout_lines }}"
#        dest: "~/Contexts/{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}-Context-of-{{ inventory_hostname }}"
#    - debug: msg="{{ context }}"
    
#    - name: switch to contexts
#      asa_command:
#        commands:
#          - changeto {{ context }}
       # provider:
       #   username: "kamil.zuk"
       #   password: "January18"
       #   authorize: yes
       #   auth_pass: "January18"
       # register: change
          
       # debug:
       #   msg: "var=change.stdout_lines"
    #  with_items: "{{ context }}"
