---
- name: 'ASA Config'
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Show contexts of the ASA
      asa_command:
        commands:
          - changeto system
          - show context
        provider:
          username: "kamil.zuk"
          password: "January18"
          authorize: yes
          auth_pass: "January18"
      register: output
    - copy: 
        content: "{{ output.stdout[0] }}"
        dest: "~/LIST OF CONTEXTS ON {{ lookup('pipe', 'date +%Y%m%d-%H%M') }} FOR HOSTS {{ inventory_hostname }}"
