---
- name: 'ASA Config'
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: retrieve contexts of the ASA of the ASA
      asa_command:
        commands:
          - changeto system
          - show run context | inc ^context
        provider:
          username: "kamil.zuk"
          password: "January18"
          authorize: yes
          auth_pass: "January18"
      register: output
    - debug: var=output.stdout_lines
    
   - name: switch to contexts and backup
     asa_commdand:
       commands:
         - changeto {{item.key}}      
     with_items:
     - "{{ output.results }}"
