---
- name: 'ASA Config'
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Show contexts of the ASA
      asa_command:
        commands:
          - changeto system
          - show context
        provider:
          username: "kamil.zuk"
          password: "January18"
          authorize: yes
          auth_pass: "January18"
    - name : Backing up all contexts
      asa_command:
        commands:
          - changeto "{{ item }}"
          - show context
      register: output
      until: result.stdout.find("Total active Security Contexts") != -1
      retries: 3
      register: {{ item }}
    - debug: var={{ item }}.stdout_lines
