---
- name: 'ASA Config'
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: retrieve contexts of the ASA 
      asa_command:
        commands:
          - changeto system
          - show run context | inc ^context
        provider:
          username: "kamil.zuk"
          password: "January18"
          authorize: yes
          auth_pass: "January18"
      register: contexts
      
      - name: switch to contexts
        asa_command:
          commands: 
            -changeto {{ contexts.stdout_lines }}
        loop: "{{ contexts.stdout_lines }}"
      
   # - name: Create Hosts
    #  add_host:
     #   name: "{{ contexts.context_name }}"
      #  group: asa_contexts
       # ansible_host: "{{ some_var_with_connection_ip }}"
       # context: "{{ context name }}"
       # any_other_hostvars: values
      #loop: contexts
    #- copy: 
     #   content: "{{ output.stdout_lines }}"
     #   dest: "/var/lib/awx/Contexts/{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}-Context-of-{{ inventory_hostname }}"
          
   #   with_lines: cat /var/lib/awx/Contexts/{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}-Context-of-{{ inventory_hostname }}  
     
   # - debug: msg="{{ item }}"
    

   #   register: contexts
      
    #- debug: msg="{{ contexts.stdout_lines }}"
      
      
#    - set_fact:
#        context={{ output.stdout_lines }}
#    - copy: 
#        content: "{{ output.stdout_lines }}"
#        dest: "~/Contexts/{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}-Context-of-{{ inventory_hostname }}"
#    - debug: msg="{{ context }}"
    
#    - name: switch to contexts
#      asa_command:
#        commands:
#          - changeto {{ context }}
       # provider:
       #   username: "kamil.zuk"
       #   password: "January18"
       #   authorize: yes
       #   auth_pass: "January18"
       # register: change
          
       # debug:
       #   msg: "var=change.stdout_lines"
    #  with_items: "{{ context }}"
