---
- name: 'ASA Config'
  hosts: all
  connection: local
  gather_facts: false
  tasks:
  
    - name: retrieve contexts of the ASA of the ASA
      asa_command:
        commands:
          - changeto system
          - show run context | inc ^context
        provider:
          username: "kamil.zuk"
          password: "January18"
          authorize: yes
          auth_pass: "January18"
      register: output
    - copy: 
        content: "{{ output.stdout[0] }}"
        dest: "~/Contexts/{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}-Context-of-{{ inventory_hostname }}"
    #- debug: var=output.stdout_lines
    
  #  - name: switch to contexts and backup
     # asa_command:
      #  commands:
       #   - changeto {{ vars[output.stdout_lines] }}    
      #  debug:
       #   msg: "{{ vars[output.stdout_lines] }}"
      #with_items: "{{ vars[output.stdout_lines] }}"
