---
- name: 'ASA Config'
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Show contexts of the ASA
      asa_command:
        commands:
          - changeto system
          - show run context | inc ^context
        provider:
          username: "kamil.zuk"
          password: "January18"
          authorize: yes
          auth_pass: "January18"
      register: output
      until: output.stdout_lines|length < 2
      # this works:
      #until: output.stdout.split()|length < 2
      retries: 3
      delay: 30
    - debug: var=output.stdout_lines
