---
- name: 'ASA Config'
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: retrieve contexts of the ASA 
      asa_command:
        commands:
          - changeto system
          - show run context | inc ^context
        provider:
          username: "kamil.zuk"
          password: "January18"
          authorize: yes
          auth_pass: "January18"
      register: contexts 
    #- copy: 
    #    content: "{{ contexts.stdout[0] }}"
    #    dest: "~/{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}-Contexts }}"
    
    - name: Create Hosts
      add_host:
        name: "test"
        group: asa_contexts
        ansible_host: all
        context: "62.25.81.100"
        any_other_hostvars: values
      run_once: true        
      with_items: "{{ contexts.stdout_lines }}"

- name: 'Backup Contexts'
  hosts: asa_contexts
  connection: local
  gather_facts: false
  tasks:
    - name: retrieve contexts of the ASA 
      asa_command:
        commands:
          - show run
        provider:
          username: "kamil.zuk"
          password: "January18"
          authorize: yes
          auth_pass: "January18"
      register: output 
               
  #  - name: backup each context
  #    asa_command:
  #      commands:
  #        - changeto "{{ context_name }}"
  #        - show run
  #    with_items: "{{ contexts.stdout_lines }}"        
   # - debug: var= contexts
         
    #- copy: 
     #   content: "{{ output.stdout_lines }}"
     #   dest: "/var/lib/awx/Contexts/{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}-Context-of-{{ inventory_hostname }}"
          
   #   with_lines: cat /var/lib/awx/Contexts/{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}-Context-of-{{ inventory_hostname }}  
     
   # - debug: msg="{{ item }}"
    

   #   register: contexts
      
    #- debug: msg="{{ contexts.stdout_lines }}"
      
      
#    - set_fact:
#        context={{ output.stdout_lines }}
#    - copy: 
#        content: "{{ output.stdout_lines }}"
#        dest: "~/Contexts/{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}-Context-of-{{ inventory_hostname }}"
#    - debug: msg="{{ context }}"
    
#    - name: switch to contexts
#      asa_command:
#        commands:
#          - changeto {{ context }}
       # provider:
       #   username: "kamil.zuk"
       #   password: "January18"
       #   authorize: yes
       #   auth_pass: "January18"
       # register: change
          
       # debug:
       #   msg: "var=change.stdout_lines"
    #  with_items: "{{ context }}"
