---
- name: 'ASA config'
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Retrieve config files from Top ASAs
      asa_command:
        commands:
          - show run
        provider:
          username: "kamil.zuk"
          password: "January18"
          authorize: yes
          auth_pass: "January18"
      register: output
    - copy: 
        content: "{{ output.stdout[0] }}"
        dest: "/home/admin/{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}-Top-{{ inventory_hostname }}"
