---
- name: 'ASA Config'
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Show contexts of the ASA
      asa_command:
        commands:
          - changeto system
          - show run context | inc ^context
        provider:
          username: "kamil.zuk"
          password: "January18"
          authorize: yes
          auth_pass: "January18"
      register: output
    #  with_lines:
     # - "{{ output.stdout_lines }}"
- debug:
    msg="{{item}}"
  with_items: "{{ dbtables_data.stdout_lines | default([]) }}"
    #- debug: var=output.stdout_lines
