---
- name: 'ASA Config'
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: retrieve contexts of the ASA of the ASA
      asa_command:
        commands:
          - changeto system
          - show run context | inc ^context
        provider:
          username: "kamil.zuk"
          password: "January18"
          authorize: yes
          auth_pass: "January18"
      register: output
      
    - set_fact:
        context={{ output.stdout[2] }}
#    - copy: 
#        content: "{{ output.stdout_lines }}"
#        dest: "~/Contexts/{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}-Context-of-{{ inventory_hostname }}"
    - debug: msg="{{ context }}"
    
   # - name: switch to contexts and backup
   #   asa_command:
   #     commands:
   #       - changeto {{ context }}    
    #    debug:
    #      msg: "{{ context }}"
    #  with_items: "{{ context }}"
