---
- name: Test reachability to 62.25.81.100 using default vrf
  ios_ping:
    dest: 62.25.81.100
- name: 'ASA config'
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Retrieve config files from Top ASAs
      asa_command:
        commands:
          - show run
        provider:
          username: "{{ login_user }}"
          password: "{{ login_pass }}"
          authorize: yes
          auth_pass: "{{ enable_pass }}"
          register: output
    - copy: 
        content: "{{ output.stdout[0] }}"
        dest: "/home/root/data/Device-Configs/asa/{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}-Top-{{ inventory_hostname }}"
