--- 
- hosts: ASAs
  gather_facts: true
  connection: local
  
  tasks:
  - name: show running config
      asa_command:
          commands:
            - show run
          provider:
          username: "kamil.zuk"
          password: "January18"
          
      when: status != 'build'
      register: output
    - copy: 
        content: "{{ output.stdout[0] }}"
        dest: "/etc/ansible/show_run_{{ inventory.hostname }}.txt"

