---
- name: Cisco ASA config
  connection: local
  hosts: ASA-01
  gather_facts: false

  tasks:
    - name: Retrieve config files from ASA
      asa_command:
        commands:
          - show run
      host: "{{ ansible_host }}"
      username: kamil.zuk
      password: January18
      register: config

  - name: save output to /etc/ansible/backups 
  copy: 
  content: "{{ config.stdout[0] }}"
  dest: "/etc/ansible/backups/show_run_{{ inventory_hostname }}.txt"
