---
- name: 'ASA config'
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Retrieve config files from ASAs
      asa_command:
        commands:
          - show run
        provider:
          username: "kamil.zuk"
          password: "January18"
      register: output
    - copy: 
        content: "{{ output.stdout[0] }}"
        dest: "/etc/ansible/show_run_{{ inventory.hostname }}.txt"
