---
- hosts: ASAs
  any_errors_fatal: True
  gather_facts: no
  remote_user: admin

  vars:
    cli:
      host: ASA-01
      username: kamil.zuk
      password: January18
      transport: cli
      authorize: yes
      auth_pass: January18

  tasks:
    - asa_command:
        commands:
          - show version
        provider: "{{ cli }}"
