---
vars:
  cli:
    host: all
    username: kamil.zuk
    password: January18
    authorize: yes
    auth_pass: January18
    transport: cli

---
- asa_command:
    commands:
      - show version
    provider: "{{ cli }}"
    context: system
