---
- name: 'ASA config'
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Retrieve config files from Top ASAs
      asa_command:
        commands:
          - show run
        provider:
          username: "{{ creds['username'] }}"
          password: "{{ creds['password'] }}"
          authorize: yes
          auth_pass: "{{ creds['auth_pass'] }}"
          register: output
    - copy: 
      register: output
    - copy: 
        content: "{{ output.stdout[0] }}"
        dest: "/etc/ansible/{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}-Top-{{ inventory_hostname }}"
