--- 
- hosts: ASAs
  gather_facts: true
  connection: local
  
  tasks:
  - name: show running config
    ios_command:
       commands:
          - show run
    host: "{{ ansible_host }}"
    username: kamil.zuk
    password: January18
    register: config
    copy:
      content: "{{ config.stdout[0] }}"
      dest: "/etc/ansible/show_run_{{ inventory.hostname }}.txt"
  
