---
- name: Cisco ASA config
  connection: local
  hosts: all
  gather_facts: false
  vars:
    cli:
      username: kamil.zuk
      password: January18
      hosts: all
      authorize: yes
      auth_pass: January18
  tasks:
    - name: run show version
      asa_command:
        commands:
          - show version
        provider: "{{ cli }}"
       register: result
