---
- name: Save Configurations (IOS)
  hosts: all
  vars:
    creds:
      username: kamil.zuk
      password: January18
  tasks:
    - ios_command:
        provider: "{{ creds }}"
        commands: show run 
      register: show_run

    - debug:
        msg: "{{ show_run }}" 
