
---
- hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Add vlan to UCSM
      ucs_vlans:
      username: ucspe
      password: ucspe
      name: vlan-test
      id: '99'
      native: 'no'
      
