
---
- hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Add vlan to UCSM
      ucs_vlans:
        hostname: 10.25.81.54
        username: ucspe
        password: ucspe
        name: vlan-test
        id: '99'
        native: 'no'
    
    - name: add vlan to vNIC Template
      ucs_vnic_template:
        hostname: 10.25.81.54
        username: ucspe
        password: ucspe
        name: DMZ_FabricA
        fabric: A
        vlans_list:
        - name: vlan-test
          native: 'no'
    
    - name: add vlan to vlan Group.
      ucs_vlan_to_group:
        hostname: 10.25.81.54
        username: ucspe
        password: ucspe
        vlangroup: DMZ-Group
        vlanname: vlan-test
        state: present
